services:
  - type: web
    name: backend-intership-health-risk-predication
    runtime: python
    repo: https://github.com/Malanagouda2005/backend_intership_health_risk_predication.git
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///health_ai.db
      - key: PYTHON_VERSION
        value: "3.11.0"
